import { Category, Brand } from '../types';

// ============================================
// Categories Seed Data
// ============================================

export const categories: Category[] = [
  {
    id: 'cat-001',
    nameAr: 'أحذية رجالي',
    nameEn: "Men's Shoes",
    slugAr: 'ahziya-rijali',
    slugEn: 'mens-shoes',
    descriptionAr: 'تشكيلة واسعة من أحذية الرجال العصرية والمريحة',
    descriptionEn: 'Wide range of modern and comfortable men shoes',
    image: '/images/categories/mens-shoes.jpg',
    icon: '👔',
    sortOrder: 1,
    isActive: true,
    metaTitleAr: 'أحذية رجالي - Smart Store',
    metaDescriptionAr: 'تسوق أحدث صيحات الأحذية الرجالي من أكبر العلامات التجارية',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-002',
    nameAr: 'أحذية نسائي',
    nameEn: "Women's Shoes",
    slugAr: 'ahziya-nisai',
    slugEn: 'womens-shoes',
    descriptionAr: 'أحذية نسائية أنيقة لمختلف المناسبات',
    descriptionEn: 'Elegant women shoes for all occasions',
    image: '/images/categories/womens-shoes.jpg',
    icon: '👠',
    sortOrder: 2,
    isActive: true,
    metaTitleAr: 'أحذية نسائي - Smart Store',
    metaDescriptionAr: 'تسوق أجمل الأحذية النسائية من علامات تجارية عالمية',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-003',
    nameAr: 'أحذية أطفال',
    nameEn: "Kids' Shoes",
    slugAr: 'ahziya-atfal',
    slugEn: 'kids-shoes',
    descriptionAr: 'أحذية أطفال مريحة ومضادة للانزلاق',
    descriptionEn: 'Comfortable and anti-slip kids shoes',
    image: '/images/categories/kids-shoes.jpg',
    icon: '👟',
    sortOrder: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-004',
    nameAr: 'أحذية رياضية',
    nameEn: 'Sports Shoes',
    slugAr: 'ahziya-riyadiya',
    slugEn: 'sports-shoes',
    descriptionAr: 'أحذية رياضية لكل أنواع التمارين والأنشطة',
    descriptionEn: 'Sports shoes for all types of exercises and activities',
    image: '/images/categories/sports-shoes.jpg',
    icon: '🏃',
    sortOrder: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-005',
    nameAr: 'صندل',
    nameEn: 'Sandals',
    slugAr: 'sandals',
    slugEn: 'sandals',
    descriptionAr: 'صندل صيفي مريح بألوان متعددة',
    descriptionEn: 'Comfortable summer sandals in multiple colors',
    image: '/images/categories/sandals.jpg',
    icon: '🩴',
    sortOrder: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-006',
    nameAr: 'إكسسوارات',
    nameEn: 'Accessories',
    slugAr: 'accessories',
    slugEn: 'accessories',
    descriptionAr: 'إكسسوارات أحذية وعناية',
    descriptionEn: 'Shoe accessories and care',
    image: '/images/categories/accessories.jpg',
    icon: '🧦',
    sortOrder: 6,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cat-007',
    nameAr: 'بوت',
    nameEn: 'Boots',
    slugAr: 'boots',
    slugEn: 'boots',
    descriptionAr: 'بوت رجالي ونسائي للموسم البارد',
    descriptionEn: 'Men and women boots for cold season',
    image: '/images/categories/boots.jpg',
    icon: '🥾',
    sortOrder: 7,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================
// Brands Seed Data
// ============================================

export const brands: Brand[] = [
  {
    id: 'brand-001',
    nameAr: 'نايكي',
    nameEn: 'Nike',
    slug: 'nike',
    logo: '/images/brands/nike.png',
    descriptionAr: 'علامة تجارية عالمية في الأحذية الرياضية',
    website: 'https://nike.com',
    isActive: true,
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-002',
    nameAr: 'أديداس',
    nameEn: 'Adidas',
    slug: 'adidas',
    logo: '/images/brands/adidas.png',
    descriptionAr: 'واحدة من أكبر العلامات التجارية في العالم',
    website: 'https://adidas.com',
    isActive: true,
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-003',
    nameAr: 'بوما',
    nameEn: 'Puma',
    slug: 'puma',
    logo: '/images/brands/puma.png',
    descriptionAr: 'تصميم عصري وأداء عالي',
    website: 'https://puma.com',
    isActive: true,
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-004',
    nameAr: 'ريبوك',
    nameEn: 'Reebok',
    slug: 'reebok',
    logo: '/images/brands/reebok.png',
    descriptionAr: 'أحذية رياضية كلاسيكية وعصرية',
    website: 'https://reebok.com',
    isActive: true,
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-005',
    nameAr: 'نيو بالانس',
    nameEn: 'New Balance',
    slug: 'new-balance',
    logo: '/images/brands/new-balance.png',
    descriptionAr: 'راحتك أولاً مع نيو بالانس',
    website: 'https://newbalance.com',
    isActive: true,
    sortOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-006',
    nameAr: 'كونفرس',
    nameEn: 'Converse',
    slug: 'converse',
    logo: '/images/brands/converse.png',
    descriptionAr: 'كلاسيك عصري لا ينتهي',
    website: 'https://converse.com',
    isActive: true,
    sortOrder: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-007',
    nameAr: 'فيلا',
    nameEn: 'Fila',
    slug: 'fila',
    logo: '/images/brands/fila.png',
    descriptionAr: 'تصميم إيطالي فريد',
    website: 'https://fila.com',
    isActive: true,
    sortOrder: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-008',
    nameAr: 'سكتشرز',
    nameEn: 'Skechers',
    slug: 'skechers',
    logo: '/images/brands/skechers.png',
    descriptionAr: 'راحة طوال اليوم',
    website: 'https://skechers.com',
    isActive: true,
    sortOrder: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-009',
    nameAr: 'هوكان',
    nameEn: 'Hoka',
    slug: 'hoka',
    logo: '/images/brands/hoka.png',
    descriptionAr: 'أحذية جري احترافية',
    website: 'https://hoka.com',
    isActive: true,
    sortOrder: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'brand-010',
    nameAr: 'ميريل',
    nameEn: 'Merrell',
    slug: 'merrell',
    logo: '/images/brands/merrell.png',
    descriptionAr: 'أحذية تถلية ومغامرات',
    website: 'https://merrell.com',
    isActive: true,
    sortOrder: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================
// Governorates (Egypt)
// ============================================

export const governorates = [
  'القاهرة',
  'الجيزة',
  'الإسكندرية',
  'الدقهلية',
  'الشرقية',
  'الغربية',
  'الفيوم',
  'بني سويف',
  'المنيا',
  'أسيوط',
  'سوهاج',
  'قنا',
  'الأقصر',
  'أسوان',
  'البحر الأحمر',
  'الإسماعيلية',
  'السويس',
  'شمال سيناء',
  'جنوب سيناء',
  'مطروح',
  'الوادي الجديد',
  'البحيرة',
  'كفر الشيخ',
  'دمياط',
];

// ============================================
// Sizes
// ============================================

export const menSizes = ['39', '40', '41', '42', '43', '44', '45', '46'];

export const womenSizes = ['35', '36', '37', '38', '39', '40', '41'];

export const kidsSizes = ['28', '29', '30', '31', '32', '33', '34', '35'];

// ============================================
// Colors
// ============================================

export const colors = [
  { nameAr: 'أسود', nameEn: 'Black', hex: '#000000' },
  { nameAr: 'أبيض', nameEn: 'White', hex: '#FFFFFF' },
  { nameAr: 'أحمر', nameEn: 'Red', hex: '#EF4444' },
  { nameAr: 'أزرق', nameEn: 'Blue', hex: '#3B82F6' },
  { nameAr: 'أخضر', nameEn: 'Green', hex: '#22C55E' },
  { nameAr: 'بني', nameEn: 'Brown', hex: '#92400E' },
  { nameAr: 'رمادي', nameEn: 'Gray', hex: '#6B7280' },
  { nameAr: 'كحلي', nameEn: 'Navy', hex: '#1E3A5F' },
  { nameAr: 'بيج', nameEn: 'Beige', hex: '#D4C5A9' },
  { nameAr: 'وردي', nameEn: 'Pink', hex: '#EC4899' },
];
