import { Product, ProductVariant } from '../types';

// ============================================
// Products Seed Data
// ============================================

export const products: Product[] = [
  // ── Nike Products ──
  {
    id: 'prod-001',
    nameAr: 'نايكي اير ماكس 2024',
    nameEn: 'Nike Air Max 2024',
    slugAr: 'nike-air-max-2024',
    slugEn: 'nike-air-max-2024',
    descriptionAr: 'حذاء رياضي كلاسيكي بتصميم عصري ونعل هواء مريح للارضيات اليومية. مثالي للمشي والجري الخفيف.',
    shortDescriptionAr: 'تصميم عصري + نعل هواء مريح',
    sku: 'NK-AM-2024',
    barcode: '5901234123457',
    categoryId: 'cat-004',
    brandId: 'brand-001',
    basePrice: 250000, // EGP 2,500.00
    costPrice: 80000,
    salePrice: 212500,
    currency: 'EGP',
    taxRate: 14,
    weight: 350,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    tags: ['-running', 'casual', 'air-max'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-002',
    nameAr: 'نايكي دانك لو',
    nameEn: 'Nike Dunk Low',
    slugAr: 'nike-dunk-low',
    slugEn: 'nike-dunk-low',
    descriptionAr: 'تصميم كلاسيكي من الستينات أعاده نايكي بأسلوب عصري. مناسب للارتداء اليومي والمناسبات.',
    shortDescriptionAr: 'كلاسيك عصري - مناسب لكل المناسبات',
    sku: 'NK-DL-2024',
    categoryId: 'cat-001',
    brandId: 'brand-001',
    basePrice: 320000,
    currency: 'EGP',
    taxRate: 14,
    weight: 320,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['classic', 'lifestyle', 'dunk'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-003',
    nameAr: 'نايكي اير فورس 1',
    nameEn: 'Nike Air Force 1',
    slugAr: 'nike-air-force-1',
    slugEn: 'nike-air-force-1',
    descriptionAr: 'أيقونة الأناقة الرياضية. تصميم أبيض ناصع ب技术ية نعل هواء.',
    shortDescriptionAr: 'أيقونة الأناقة - أبيض كلاسيك',
    sku: 'NK-AF1-2024',
    categoryId: 'cat-001',
    brandId: 'brand-001',
    basePrice: 280000,
    currency: 'EGP',
    taxRate: 14,
    weight: 370,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['classic', 'lifestyle', 'air-force'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ── Adidas Products ──
  {
    id: 'prod-004',
    nameAr: 'أديداس ألترا بوست',
    nameEn: 'Adidas Ultraboost',
    slugAr: 'adidas-ultraboost',
    slugEn: 'adidas-ultraboost',
    descriptionAr: 'تقنية بوست المطورة توفر راحة استثنائية وردود فعل ممتازة. مناسب للجري اليومي.',
    shortDescriptionAr: 'راحة استثنائية مع تقنية بوست',
    sku: 'AD-UB-2024',
    barcode: '4064035678901',
    categoryId: 'cat-004',
    brandId: 'brand-002',
    basePrice: 320000,
    costPrice: 120000,
    currency: 'EGP',
    taxRate: 14,
    weight: 310,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    tags: ['running', 'boost', 'ultraboost'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-005',
    nameAr: 'أديداس سوبرستار',
    nameEn: 'Adidas Superstar',
    slugAr: 'adidas-superstar',
    slugEn: 'adidas-superstar',
    descriptionAr: 'كلاسيك أديداس الشهير بلمعة القشرة. مناسب لكل المناسبات.',
    shortDescriptionAr: 'كلاسيك أديداس - لمعة القشرة',
    sku: 'AD-SS-2024',
    categoryId: 'cat-001',
    brandId: 'brand-002',
    basePrice: 240000,
    currency: 'EGP',
    taxRate: 14,
    weight: 340,
    status: 'active',
    isActive: true,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['classic', 'lifestyle', 'superstar'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ── Puma Products ──
  {
    id: 'prod-006',
    nameAr: 'بوما RS-X',
    nameEn: 'Puma RS-X',
    slugAr: 'puma-rs-x',
    slugEn: 'puma-rs-x',
    descriptionAr: 'تصميم مستقبلي بألوان جريئة. نعل RS مطور للراحة اليومية.',
    shortDescriptionAr: 'تصميم مستقبلي + ألوان جريئة',
    sku: 'PM-RSX-2024',
    categoryId: 'cat-001',
    brandId: 'brand-003',
    basePrice: 180000,
    currency: 'EGP',
    taxRate: 14,
    weight: 360,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    tags: ['retro', 'lifestyle', 'rs-x'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-007',
    nameAr: 'بوما سويد',
    nameEn: 'Puma Suede',
    slugAr: 'puma-suede',
    slugEn: 'puma-suede',
    descriptionAr: 'كلاسيك بوما بجلد السويد الفاخر. مريح وأنيق.',
    shortDescriptionAr: 'كلاسيك سويد فاخر',
    sku: 'PM-SD-2024',
    categoryId: 'cat-001',
    brandId: 'brand-003',
    basePrice: 160000,
    currency: 'EGP',
    taxRate: 14,
    weight: 330,
    status: 'active',
    isActive: true,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['classic', 'suede', 'lifestyle'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ── Women Specific ──
  {
    id: 'prod-008',
    nameAr: 'نايكي ريسن 6',
    nameEn: 'Nike Revolution 6',
    slugAr: 'nike-revolution-6-womens',
    slugEn: 'nike-revolution-6-womens',
    descriptionAr: 'حذاء رياضي نسائي خفيف ومريح مع نعل مرن للحركة الطبيعية.',
    shortDescriptionAr: 'خفيف ومريح - للحركة الطبيعية',
    sku: 'NK-RV6-W-2024',
    categoryId: 'cat-002',
    brandId: 'brand-001',
    basePrice: 190000,
    currency: 'EGP',
    taxRate: 14,
    weight: 250,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    tags: ['womens', 'running', 'lightweight'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-009',
    nameAr: 'أديداس كلايمات كول',
    nameEn: 'Adidas Climate Cool',
    slugAr: 'adidas-climate-cool-womens',
    slugEn: 'adidas-climate-cool-womens',
    descriptionAr: 'صندل نسائي بتصميم عصري مع تقنية تبريد. مثالي للصيف.',
    shortDescriptionAr: 'صندل صيفي بتقنية تبريد',
    sku: 'AD-CC-W-2024',
    categoryId: 'cat-005',
    brandId: 'brand-002',
    basePrice: 120000,
    currency: 'EGP',
    taxRate: 14,
    weight: 200,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    tags: ['womens', 'sandals', 'summer'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ── Kids ──
  {
    id: 'prod-010',
    nameAr: 'نايكي توتال إلكترو',
    nameEn: 'Nike Total Electro Kids',
    slugAr: 'nike-total-electro-kids',
    slugEn: 'nike-total-electro-kids',
    descriptionAr: 'حذاء أطفال رياضي بتصميم ملون ومريح. سهل الارتداء والخلع.',
    shortDescriptionAr: 'ملون ومريح - سهل الارتداء',
    sku: 'NK-TE-K-2024',
    categoryId: 'cat-003',
    brandId: 'brand-001',
    basePrice: 120000,
    currency: 'EGP',
    taxRate: 14,
    weight: 180,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['kids', 'colorful', 'easy-wear'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-011',
    nameAr: 'ريبوك رويال كلاسيك',
    nameEn: 'Reebok Royal Classic Kids',
    slugAr: 'reebok-royal-classic-kids',
    slugEn: 'reebok-royal-classic-kids',
    descriptionAr: 'كلاسيك ريبوك بحجم أطفال. مريح ومتين.',
    shortDescriptionAr: 'كلاسيك صغير - متين ومريح',
    sku: 'RB-RC-K-2024',
    categoryId: 'cat-003',
    brandId: 'brand-004',
    basePrice: 95000,
    currency: 'EGP',
    taxRate: 14,
    weight: 160,
    status: 'active',
    isActive: true,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    tags: ['kids', 'classic', 'durable'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ── Sandals ──
  {
    id: 'prod-012',
    nameAr: 'سكتشرز أرينا',
    nameEn: 'Skechers Arena',
    slugAr: 'skechers-arena',
    slugEn: 'skechers-arena',
    descriptionAr: 'صندل مريح بتقنية أورثليت. مثالي للمشي اليومي.',
    shortDescriptionAr: 'صندل أورثليت - للمشي اليومي',
    sku: 'SK-AR-2024',
    categoryId: 'cat-005',
    brandId: 'brand-008',
    basePrice: 85000,
    currency: 'EGP',
    taxRate: 14,
    weight: 220,
    status: 'active',
    isActive: true,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['sandals', 'comfortable', 'ortholite'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // ── Boots ──
  {
    id: 'prod-013',
    nameAr: 'ميريل مويناب',
    nameEn: 'Merrell Moab',
    slugAr: 'merrell-moab',
    slugEn: 'merrell-moab',
    descriptionAr: 'بوت تถلي مقاوم للماء. مناسب للمغامرات والطبيعة.',
    shortDescriptionAr: 'بوت تถلي - مقاوم للماء',
    sku: 'MR-MOAB-2024',
    categoryId: 'cat-007',
    brandId: 'brand-010',
    basePrice: 280000,
    currency: 'EGP',
    taxRate: 14,
    weight: 500,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    tags: ['hiking', 'waterproof', 'outdoor'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-014',
    nameAr: 'نيو بالانس فويجر',
    nameEn: 'New Balance Fresh Foam Roav',
    slugAr: 'new-balance-fresh-foam-roav',
    slugEn: 'new-balance-fresh-foam-roav',
    descriptionAr: 'حذاء رياضي بنعل فريش فوم السميك. راحة استثنائية.',
    shortDescriptionAr: 'فريش فوم - راحة استثنائية',
    sku: 'NB-FFR-2024',
    categoryId: 'cat-004',
    brandId: 'brand-005',
    basePrice: 220000,
    currency: 'EGP',
    taxRate: 14,
    weight: 290,
    status: 'active',
    isActive: true,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['running', 'fresh-foam', 'comfortable'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-015',
    nameAr: 'كونفرس تشاك تايلور',
    nameEn: 'Converse Chuck Taylor',
    slugAr: 'converse-chuck-taylor',
    slugEn: 'converse-chuck-taylor',
    descriptionAr: 'كلاسيك خالد لا ينتهي. مناسب لكل الإطلالات.',
    shortDescriptionAr: 'كلاسيك خالد - لكل الإطلالات',
    sku: 'CV-CT-2024',
    categoryId: 'cat-001',
    brandId: 'brand-006',
    basePrice: 150000,
    currency: 'EGP',
    taxRate: 14,
    weight: 300,
    status: 'active',
    isActive: true,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    tags: ['classic', 'canvas', 'converse'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================
// Product Variants Seed Data
// ============================================

export const productVariants: ProductVariant[] = [
  // Nike Air Max 2024 variants
  {
    id: 'var-001',
    productId: 'prod-001',
    sku: 'NK-AM-2024-BLK-42',
    size: '42',
    color: 'أسود',
    colorHex: '#000000',
    price: 250000,
    salePrice: 212500,
    stock: 45,
    reservedStock: 2,
    lowStockThreshold: 10,
    images: [
      { id: 'img-001', productId: 'prod-001', url: '/images/products/nike-air-max-black-1.jpg', altAr: 'نايكي اير ماكس اسود - منظر امامي', width: 800, height: 800, sortOrder: 1, isPrimary: true, createdAt: new Date() },
      { id: 'img-002', productId: 'prod-001', url: '/images/products/nike-air-max-black-2.jpg', altAr: 'نايكي اير ماكس اسود - منظر جانبي', width: 800, height: 800, sortOrder: 2, isPrimary: false, createdAt: new Date() },
      { id: 'img-003', productId: 'prod-001', url: '/images/products/nike-air-max-black-3.jpg', altAr: 'نايكي اير ماكس اسود - منظر خلفي', width: 800, height: 800, sortOrder: 3, isPrimary: false, createdAt: new Date() },
    ],
    model3D: '/models/nike-air-max.glb',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'var-002',
    productId: 'prod-001',
    sku: 'NK-AM-2024-WHT-42',
    size: '42',
    color: 'أبيض',
    colorHex: '#FFFFFF',
    price: 250000,
    stock: 30,
    reservedStock: 0,
    lowStockThreshold: 10,
    images: [
      { id: 'img-004', productId: 'prod-001', url: '/images/products/nike-air-max-white-1.jpg', altAr: 'نايكي اير ماكس ابيض - منظر امامي', width: 800, height: 800, sortOrder: 1, isPrimary: true, createdAt: new Date() },
    ],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'var-003',
    productId: 'prod-001',
    sku: 'NK-AM-2024-RED-42',
    size: '42',
    color: 'أحمر',
    colorHex: '#EF4444',
    price: 250000,
    stock: 20,
    reservedStock: 1,
    lowStockThreshold: 10,
    images: [
      { id: 'img-005', productId: 'prod-001', url: '/images/products/nike-air-max-red-1.jpg', altAr: 'نايكي اير ماكس احمر - منظر امامي', width: 800, height: 800, sortOrder: 1, isPrimary: true, createdAt: new Date() },
    ],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Adidas Ultraboost variants
  {
    id: 'var-004',
    productId: 'prod-004',
    sku: 'AD-UB-2024-BLK-42',
    size: '42',
    color: 'أسود',
    colorHex: '#000000',
    price: 320000,
    stock: 35,
    reservedStock: 0,
    lowStockThreshold: 10,
    images: [
      { id: 'img-006', productId: 'prod-004', url: '/images/products/adidas-ultraboost-black-1.jpg', altAr: 'أديداس ألترا بوست اسود', width: 800, height: 800, sortOrder: 1, isPrimary: true, createdAt: new Date() },
    ],
    model3D: '/models/adidas-ultraboost.glb',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
